# Generated by Django 4.2.11 on 2024-03-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Trayectory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('taxi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.taxi')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
